version: "3"

networks:
  clean-arch-network:
    driver: bridge

services:
  db:
    image: postgres
    container_name: foodtruckdb
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "foodtruckdb"
    networks:
      - clean-arch-network
    ports:
      - 5433:5432